services:
  web:
    build:
      context: .
      dockerfile: Containerfile
      target: production
    restart: unless-stopped
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      PORT: 3000
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"

      DATABASE_URL: postgresql://forem:${POSTGRES_PASSWORD}@postgres:5432/forem_production

      REDIS_URL: redis://redis:6379/1
      REDIS_SIDEKIQ_URL: redis://redis:6379/3
      REDIS_SESSIONS_URL: redis://redis:6379/4
      REDIS_RPUSH_URL: redis://redis:6379/5

      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    volumes:
      - forem_uploads:/opt/apps/forem/public/uploads

    expose:
      - "3000"

  sidekiq:
    build:
      context: .
      dockerfile: Containerfile
      target: production
    restart: unless-stopped
    command: bundle exec sidekiq -t 25
    environment:
      RAILS_ENV: production
      NODE_ENV: production

      DATABASE_URL: postgresql://forem:${POSTGRES_PASSWORD}@postgres:5432/forem_production

      REDIS_URL: redis://redis:6379/1
      REDIS_SIDEKIQ_URL: redis://redis:6379/3
      REDIS_SESSIONS_URL: redis://redis:6379/4
      REDIS_RPUSH_URL: redis://redis:6379/5

      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    volumes:
      - forem_uploads:/opt/apps/forem/public/uploads

  postgres:
    image: pgvector/pgvector:pg13-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: test123456789
      POSTGRES_DB: forem_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U forem -d forem_production"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
  redis_data:
  forem_uploads: