version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:yourpostgrespassword@db:5432/forem_production
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}  # Generate with `bundle exec rails secret`
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}      # Generate with `bundle exec rails secret`
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    restart: unless-stopped
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:yourpostgrespassword@db:5432/forem_production
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: yourpostgrespassword
      POSTGRES_DB: forem_production
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s

volumes:
  postgres_data:
  redis_data: